# Generated by Django 4.1.7 on 2023-05-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_sku_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('-is_feature',)},
        ),
    ]
