# Generated by Django 4.1.7 on 2023-05-28 11:30

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_in_stock_product_maximum_purchase_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='/media/products/default.png', upload_to=store.models.product_image_path),
        ),
    ]
