# Generated by Django 4.1.7 on 2023-06-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_category_last_modified_by_product_last_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
    ]
