# Generated by Django 4.1.7 on 2023-05-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_billing_status_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
