# Generated by Django 4.1.7 on 2023-05-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
