# Generated by Django 4.1.7 on 2023-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderrefund_options_order_total_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefund',
            name='reason',
            field=models.TextField(default='Default reason'),
            preserve_default=False,
        ),
    ]
