# Generated by Django 4.1.7 on 2023-05-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderdelivery_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrefund',
            old_name='last_modified_by',
            new_name='created_by',
        ),
    ]
