# Generated by Django 4.1.7 on 2023-05-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session_id',
        ),
    ]
