# Generated by Django 4.1.7 on 2023-06-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_historicalorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderdelivery',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
