# Generated by Django 4.1.7 on 2023-04-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_siteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
