# Generated by Django 4.1.7 on 2023-04-20 07:02

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_siteinfo_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', main.models.LanguageField(choices=[('ru', 'Russian'), ('az', 'Azerbaijani'), ('en', 'English')], default='az', max_length=2)),
                ('about', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Site Infos',
            },
        ),
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name_plural': 'Site Infos'},
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='about',
        ),
    ]
