# Generated by Django 4.1.7 on 2023-04-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitetext_alter_siteinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='tiktok_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
