# Generated by Django 4.1.7 on 2023-05-09 20:19

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_siteinfo_tiktok_link_siteinfo_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', main.models.LanguageField(choices=[('az', 'Azerbaijani'), ('ru', 'Russian'), ('en', 'English')], default='az', max_length=2)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='sitetext',
            options={'verbose_name_plural': 'Site Texts'},
        ),
        migrations.AddField(
            model_name='sitetext',
            name='privacy_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='return_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
