# Generated by Django 4.1.7 on 2023-05-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_question_answer_alter_sitetext_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='breadcrumb_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
