# Generated by Django 4.1.7 on 2023-05-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_siteinfo_about_image_siteinfo_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='about_image',
            field=models.ImageField(blank=True, default='site/about_image_default.jpg', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='banner_image',
            field=models.ImageField(blank=True, default='site/banner_default.jpg', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='breadcrumb_image',
            field=models.ImageField(blank=True, default='site/breadcrumb_default.jpg', null=True, upload_to='site/'),
        ),
    ]
