# Generated by Django 4.1.7 on 2023-06-02 18:42

from django.db import migrations
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_last_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='language',
            field=services.models.LanguageField(choices=[('az', 'Azerbaijani'), ('ru', 'Russian'), ('en', 'English')], default='az', max_length=2),
        ),
    ]
