# Generated by Django 4.1.7 on 2023-06-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_historicalservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalService',
        ),
    ]
