# Generated by Django 4.1.7 on 2023-05-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Editor', 'Editor'), ('Operator', 'Operator'), ('Staff', 'Staff')], default='Staff', max_length=50),
        ),
    ]
